### ISSUE TITLE
Icon size issue on macOS

### ISSUE THREAD

**Issue by pawelwiejkut** [andau/abapCI#11]
Hi guys,

On macos icons added by plugin to toolbar are too big. This cause that toolbar is few times bigger as usual. Check out screenshot.
<img width="688" alt="zrzut ekranu 2018-11-11 o 08 42 15" src="https://user-images.githubusercontent.com/11619019/48310332-fb0eca00-e58d-11e8-9e98-bed08860880e.png">

**Comment by andau** [comment]
Its good when the plugin gets recognised on the UI, but of cource not that much :-) 

I am planning to make the next release no later than next week and with that I will solve it. 
Hopefully I find the reason for the bigger items (seems to be something related to the resolution) 
If I do not find the reason I am planning to add a checkbox which can hide these two icons. 

Greetings and a bit of patience please, Andreas

**Comment by andau** [comment]
Solved in the last release. The plugin loads automatically, thus the first button is not necessary anymore. The second one can be found in the project explorer menu, which is the  better location as  this feature is dependent on  the selected project

**Comment by pawelwiejkut** [comment]
Thank you !
