### ISSUE TITLE
Asynchronous ATC check/unit tests for whole package

### ISSUE THREAD

**Issue by FreHu** [andau/abapCI#14]
Running ATC check or unit tests for a package seems to be a synchronous process which will make the whole IDE freeze until the checks are done.

**Comment by andau** [comment]
I think you mean the manual trigger in the "AbapCi Main View". Yes they are synchronous. As the target of the plugin is to automatically run the unit tests and  ATC checks, I see these manual triggers only as minor help functions , which rarely will be needed, therefore for me its not worth the effort to make them asynchronously.
