### ISSUE TITLE
Download-and-Install-Plugin-From-Zip

### ISSUE THREAD

**Issue by gepparta** [andau/abapCI#15]
Would be helpful to have a installation possibility for this plugin like it is available here:
https://github.com/cucumber/cucumber-eclipse/wiki/Download-and-Install-Plugin-From-Zip

In situations where your are at your client and are not allowed to connect your eclipse to eclipse marketplace, but you have the possibility to use a browser for surfing. 

I'm currently in such a situation :-(
 
What do you think?

**Comment by gepparta** [comment]
Hi Andreas,
thanks for the hint.
Unfortunately it's not working for me.

In Step 2 I don't see the option do export as "Deployable Features".

I have tried it in a different way, as Installation from a local zip, and saw that my eclipse on the client site has not the right "type". Because  osgi.bundle and other dependencies are missing. 
I will clarify this first and close this issue for now.

Kind regards
Alex

**Comment by andau** [comment]
What also should work is to download the entire Repository to your local drive as zip - See button in the first screenshot. 
Afterwards you can install the plugin like in step 3 - but If you understand you right thats also not working in your Eclipse installation. 

Please feel free to contact me again if there is something more I can do. 

Grüße, Andreas 
 
![image](https://user-images.githubusercontent.com/23290618/49031815-4e4a6480-f1ab-11e8-826d-4d1753e861ec.png)


![image](https://user-images.githubusercontent.com/23290618/49031772-34108680-f1ab-11e8-826a-f2ae3cfe9f65.png)
