### ISSUE TITLE
Endless ATC Check Loading

### ISSUE THREAD

**Issue by timostark** [andau/abapCI#25]
Hi,

**What Happens**: ATC checks are only executed once, and afterwards in endless loading state
**Expected**: Activation always leads to a re-evaluation of ATC checks

I am using Eclipse Oxygen.3a (4.7.3a) with ABAP Plugin Version 2.102.6. Is that identical to the version you are using?

**Steps to reproduce**
Create report with clear ATC error in it --> activate
![image](https://user-images.githubusercontent.com/19237828/53325001-89f7e600-38e2-11e9-9281-570ce5cc7b5a.png)

--> Error is reported
![image](https://user-images.githubusercontent.com/19237828/53325044-a3009700-38e2-11e9-8936-0e0c445cf165.png)

--> Comment the line
![image](https://user-images.githubusercontent.com/19237828/53325058-ad229580-38e2-11e9-8c8c-695d3dfdcefd.png)

--> Activate again --> Error is still there: AbapCI is claimed to be always "active"
![image](https://user-images.githubusercontent.com/19237828/53325124-d17e7200-38e2-11e9-9f54-b9895f6c1a39.png)

Preferences:
![image](https://user-images.githubusercontent.com/19237828/53325179-f96dd580-38e2-11e9-80d6-7367867d6116.png)
![image](https://user-images.githubusercontent.com/19237828/53325189-fd99f300-38e2-11e9-95e1-011dc8e680b1.png)

Thanks,
Timo

**Comment by andau** [comment]
Tried it with Eclipse 2018-09 and the latest version of ADT 2.102.5. 
With this setup I could not reproduce the error.
