### ISSUE TITLE
ABAPCI Interfers in HANA Modeler

### ISSUE THREAD

**Issue by timostark** [andau/abapCI#26]
Hi,

Opening a Project in HANA Repository perspective (HANA Developer), leads to the coloring question.
Would be good, if ABAPCi is only reacting on ABAP projects.

![image](https://user-images.githubusercontent.com/19237828/53334078-fcbf8c00-38f7-11e9-8578-0cb8c2de4c88.png)

Thanks,
Timo

**Comment by andau** [comment]
Hi Timo!

The coloring is intended to be usable also for projects other than ABAP. For example I use them for my JAVA projects and some others use them also for HANA projects. 

If you do not want to have them colored you can use the default  setup "Do not color this project" or there is also the option to entirely disable the project coloring for new projects at the end of the configuration dialog. 

Greetings, Andreas

**Comment by kjetil-kilhavn** [comment]
I agree with the original poster. I did not expect the "ABAP Continuous Integration" plug-in to interfere with projects completely unrelated to SAP (which it currently does).
