### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by FreHu** [andau/abapCI#27]
Hi,

when installing the plugin, I get the error
```Cannot complete the install because one or more required items could not be found.
Software currently installed: ABAP Continuous Integration 0.5.5.2 (com.abapci.feature.feature.group 0.5.5.2)
Missing requirement: com.abapci.plugin 0.5.5.2 requires 'osgi.bundle; org.junit.platform.commons 0.0.0' but it could not be found
Cannot satisfy dependency:
From: ABAP Continuous Integration 0.5.5.2 (com.abapci.feature.feature.group 0.5.5.2)
To: org.eclipse.equinox.p2.iu; com.abapci.plugin [0.5.5.2,0.5.5.2]
```

is there something wrong with my installation or the plugin?

**Comment by Lexchess** [comment]
I found a fix for this error at the following site:
https://stackoverflow.com/questions/2550755/how-to-install-jdt-core-in-eclipse-locally

1. Go to "Help", then go to "Install New Software", and the install dialog pops up.
2. Click on the dropdown where it says "type or select a site"
3. Your list may be different, but I chose "--All Available Sites--"
4. Go to "Programming Languages" and choose "Eclipse Java Development Tools"
