### ISSUE TITLE
CI is not working from eclipse

### ISSUE THREAD

**Issue by Sucheta2** [andau/abapCI#28]
I am trying the following steps. Please guide me where I am going wrong. 

Installed eclipse then ABAP CI plug in. I have a class with unit test class. When I am executing abap unit test it is showing the exception. But I have configured my package for auto trigger of unti test after activation. But it is not working.

Please find the attachment. 
[ABAP CI.docx](https://github.com/andau/abapCI/files/3411620/ABAP.CI.docx)

**Comment by andau** [comment]
Hmm, strange. The only thing I could immagine is, that the Unit tests are only triggered if there was a real change on the source code (for example adding a blank in the source code is not detected)
