### ISSUE TITLE
#FeatureRequest

### ISSUE THREAD

**Issue by TimoJohn** [andau/abapCI#3]
Hello Andreas,
 it would be helpful if we could define in the settings of ABAP CI, until wich levels of:
- Surverity ( medium; critical, ....) and Timing we wand unit tests to be executes automatically

Thanks for good work so far 
Timo

**Comment by andau** [comment]
Severity and Timing granularity are of course desireable features, but actually there are a lot of other stuff to do - the whole thing is still in beta mode. 
Pull requests welcome :-)

**Comment by andau** [comment]
I tried to include this feature into the plugin. On the Eclipse site its possible to implement. The ADT SDK provides the function to set the severity and duration of the unit tests.
But if I understand it right the ADT SDK checks before calling the rest service for the existence of the backend version which supports this granularity - there are three versions. On my 7.50 system there is only one version available which does not supports to set severity and duration. So I am not able to test it.
