### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by timostark** [andau/abapCI#6]
Dear Andau,

First thanks for your work in that open source plugin.
We are currently evaluating the use of it. Most probably we will need a few extensions (e.g. hierarchical control for packages, as mentioned in issue 5, or also better control of ATC Runs).

Of course I'd like to make a normal pull request for that - I am however not really sure if I am allowed to do so, due to the missing license.
Can you please clarify the license and add it to the git repository?

Thanks,
Timo

**Comment by andau** [comment]
Hi Timo!
I added the licence, its the standard MIT licence, so feel free to use the plugin in the mode you want. 
Regarding the ATC checks, please see the notes in the other issue you opened.

Greetings, Andreas
